name: Build

on:
  push:
    paths-ignore:
      - 'LICENSE'
      - 'README.md'
      - 'publishing.gradle'

jobs:
  build:
    name: Build and Upload Artifact
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
        uses: actions/checkout@v2

      - name: Gather Gradle properties
        uses: madhead/read-java-properties@latest
        id: gradle_properties
        with:
          file: gradle.properties
          all: true

      - name: Retrieve SHA short
        id: vars
        shell: bash
        run: echo "SHA_SHORT=$(git rev-parse --short HEAD)" >> $GITHUB_OUTPUT

      - name: Change mod version
        run: sed -i "s/mod_version.*=.*/mod_version = ${{ steps.gradle_properties.outputs.mod_version }}-${{ steps.vars.outputs.SHA_SHORT }}/g" gradle.properties

      - name: Setup Temurin JDK 8
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: gradle

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          arguments: build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2.2.3
        with:
          name: ColorfulTooltips-${{ steps.gradle_properties.outputs.mod_version }}
          path: build/libs